spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: api-1
          uri: lb://WELCOME-MS
          predicates:
            - Path=/welcome/**

        - id: api-2
          uri: lb://GREET-MS
          predicates:
            - Path=/greet/**

server:
  port: 3333
